name: tdmpc2
channels:
  - pytorch
  # - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - glew=2.2.0
  - glib=2.78.4
  - pip=24.0
  - python=3.11
  - pytorch=2.6.* #0.dev20241112
  - pytorch-cuda=12.4
  # Move what we can from pip to conda (exact pins)
  - gymnasium=0.29.1
  - ffmpeg  # provide system ffmpeg binary for video encoding
  - imageio=2.34.1
  - imageio-ffmpeg=0.4.9
  - h5py=3.11.0
  - hydra-core=1.3.2
  - hydra-submitit-launcher=1.2.0
  - submitit=1.5.1
  - omegaconf=2.3.0
  - absl-py  # required by dm-control
  - moviepy=1.0.3
  - numpy=1.24.4
  - kornia
  - termcolor=2.4.0
  - tqdm=4.66.4
  - pandas=2.0.3
  - wandb
  
  - pip:
    - glfw==2.7.0
    - dm-control
    - ffmpeg==1.4
    - mujoco==3.1.2
    - tensordict
    - torchrl
    # (unmaintained but required for maniskill2/meta-world)
    # - "cython<3"
    # - wheel==0.38.0
    # - setuptools==65.5.0
    # - mujoco==2.3.1
    # - mujoco-py==2.1.2.14
    # - gym==0.21.0
    ####################
    # ManiSkill2:
    # (requires gym==0.21.0 which occasionally breaks)
    # - mani-skill2==0.4.1
    ####################
    # Meta-World:
    # (requires gym==0.21.0 which occasionally breaks)
    # - git+https://github.com/Farama-Foundation/Metaworld.git@04be337a12305e393c0caf0cbf5ec7755c7c8feb
    ####################
    # MyoSuite:
    # - myosuite
    ####################
    # Classic MuJoCo/Box2d:
    # - swig
    # - gymnasium[box2d]
    ####################